name: CI

on:
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  auto-assigner:
    # Run for all PRs (internal + fork)
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR
        uses: toshimaru/auto-author-assign@v2.1.1

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code safely
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref:        ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Dummy lint step
        run: |
          echo "Running CI..."
          python --version
